console.log("Site made by CodeHaven");

width = window.innerWidth;
console.log(width);

if (width <= 890) {
    console.log("Mobile activated");

    document.getElementById("home").innerHTML = "<div class='pf'><div class='pft'><h1>Océane Hair Studio</h1><div class='stars'><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span></div><img class='pimg' src='salon.jpg' alt='salon photo'><div class='dets'><p>WOMEN - MEN - KIDS SERVICES</p><p>Hair cutting and styling <br> Colouring &amp; Keratin Treatment <br> Barber services</p><a class='pfta' target='_blank' href='https://www.fresha.com/a/oceane-hair-studio-killarney-heights-19-cashel-crescent-nb01ns6s/booking'>See all services and prices</a></div></div></div>";
    document.getElementById("ri").innerHTML = "<div id='carouselExampleIndicators' class='carousel slide' data-ride='carousel'><ol class='carousel-indicators'><li data-target='#carouselExampleIndicators' data-slide-to='0' class='active'></li><li data-target='#carouselExampleIndicators' data-slide-to='1'></li><li data-target='#carouselExampleIndicators' data-slide-to='2'></li></ol><div class='carousel-inner'><div class='carousel-item active'><img class='d-block w-100' src='results1.jpg' alt='First slide'></div><div class='carousel-item'><img class='d-block w-100' src='results2.jpg' alt='Second slide'></div><div class='carousel-item'><img class='d-block w-100' src='results3.jpg' alt='Third slide'></div></div><a class='carousel-control-prev' href='#carouselExampleIndicators' role='button' data-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='sr-only'>Previous</span></a><a class='carousel-control-next' href='#carouselExampleIndicators' role='button' data-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='sr-only'>Next</span></a></div>";
    document.getElementById("ok").innerHTML = "<div id='carouselExampleIndicators' class='carousel slide' data-ride='carousel'><ol class='carousel-indicators'><li data-target='#carouselExampleIndicators' data-slide-to='0' class='active'></li><li data-target='#carouselExampleIndicators' data-slide-to='1'></li><li data-target='#carouselExampleIndicators' data-slide-to='2'></li></ol><div class='carousel-inner iok'><div class='carousel-item active'><div class='rit'><h4>Bodhi S.</h4><p>16 feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane was amazing! Her foils and colour are beautiful. Very happy with the end result :)</p></div><div class='carousel-item'><div class='rit'><h4>Bodhi S.</h4><p>16 feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane was amazing! Her foils and colour are beautiful. Very happy with the end result :)</p></div><div class='carousel-item'><div class='rit'><h4>Bodhi S.</h4><p>16 feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane was amazing! Her foils and colour are beautiful. Very happy with the end result :)</p></div></div><a class='carousel-control-prev' href='#carouselExampleIndicators' role='button' data-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='sr-only'>Previous</span></a><a class='carousel-control-next' href='#carouselExampleIndicators' role='button' data-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='sr-only'>Next</span></a></div>";
}

 